### ISSUE TITLE
Differences

### ISSUE THREAD

**Issue by DataExplorerUser** [0lru/p3ui#1]
Hey there,

I just found out about this library.

How is this aimed to be different from other libraries based on imgui such as [pyimgui ](https://github.com/pyimgui/pyimgui) and [dearpygui](https://github.com/hoffstadt/DearPyGui/)?

Thanks!

**Comment by 0lru** [comment]
DearPyGui is pure Python. It's neither object-oriented nor C++. There was a discussion and somebody who started this: https://github.com/mwerezak/DearPyGui-Obj. However. This isn't usable in C++ still. Having a node tree gives you various optimization abilities. On the other hand, PyImGui is a pure "1:"-wrapper DearImGui. Indeed, I started two projects with DearPyGui. Liked the performance in terms of fps/smoothness there. But my issues and the reason for starting p3 were:
* Needed some way to "throttle down" the GPU-fps if no user input is given (for reducing thermal heat :-D on a pc that runs 24/7)
* Want a nice(er), clean API for my own applications. As an example, I don't like global variables
* Want to be able to use it in C++
* Had a memory leak with DearPyGui and wasn't able to fix it in a reasonable time
* Want to be independent of several design choices made by DearPyImGui
* Want to be able to optimize it later. Again.. reduce GPU usage and thermal heat and only redraw if something changed. Maybe even switching the underlying framework (ImGui) to something different. But that's kind of utopic, I know..
* Had some fun with it :-)

**Comment by DataExplorerUser** [comment]
Alright, thanks for the quick and elaborate response. It would be interesting to see some GIFs once you release it. Starring for now!

**Comment by 0lru** [comment]
At long last, I'd prefer to have something like [sciter](https://sciter.com/) with ImPlot for C++/Python (and with "no dart"..) plus some "simple" (and simple to use-) widgets like in ImGui, but "OpenSource".. think the closest match was/is [skui](https://github.com/skui-org/skui) or [azul](https://github.com/fschutt/azul). Kivy may be nice but also had some trouble while using it. CSS/Html addresses so many things... not sure if I like UI-Development at all :-). What do you think?

**Comment by DataExplorerUser** [comment]
Sciter, skui and azul look interesting for sure!

To be honest, as an beginner/intermediate level Python developer (just as a hobby and no C++ experience) I am mainly looking for a open source framework that is modern, responsive and stable with a decent feature set. Tkinter looks like Windows 98 and the PyQt license is iffy. Kivy looks pretty good, but has a reputation for driving people mad.

I have my personal preferences as to what a graph should look like (I prefer a minimalistic style) to convey a message or API style. However, I will take any framework that offers the basics that I mentioned and that just works. I am not capable (or willing to spend the time) to create my own GUI framework.

From a open source community perspective, I'd like to see people collaborate more, rather that fork projects or create new projects that, from a bigger perspective, are pretty similar. It's unfortunate to see that the desktop GUIs for Python aren't as mature as I would expect considering Python is the most popular programming language in the world. Hence my (implied) question, why not collaborate with the developers of pyimgui or dearpygui instead of rolling your own. Of course, it can be fun and educational to create something by yourself,  but so can collaborating on a project.

**Comment by 0lru** [comment]
> It's unfortunate to see that the desktop GUIs for Python aren't as mature as I would expect

Indeed. That's why azul looks promising to me. Anyhow, "IM" with implot, the name ays it all, seems
to be a good interim solution :-).

**Comment by hoffstadt** [comment]
### Few small notes I wanted to respond to:

> Needed some way to "throttle down" the GPU-fps if no user input is given (for reducing thermal heat :-D on a pc that runs 24/7)

This is a good idea. I considered but never went to far into it (in particular the MacOs and Metal stuff was new for me).

> Want to be able to use it in C++. The code in DearPyImGui is ok, but heavily mixed with CPython.

We looked at doing this a while back but it turned out to be a mess to decouple CPython (which you noticed). Plus, we realized that in C++, we really preferred immediate mode and reverted back to using pure imgui.

> Had a memory leak with DearPyGui and wasn't able to fix it in a reasonable time (Maybe it'd be better to use pybind11 there as well?)

Did you report this? If not, please do so we can fix it.

> Want to be independent of several design choices made by DearPyImGui. I mean.. I'm currently experimenting a lot (model binding, async etc.). I think this would take a long long time using DearPyImGui if that's even possible.

Understandable.

### Other

I do wish you would have brought up some of your concerns so that we could have collaborated a bit.

**Comment by 0lru** [comment]
> This is a good idea.
Think it's substantial for some applications and also environmentally more friendly.
A gaming-like render loop is not required at all. If I use glfwWaitEvents (or consorts)
the CPU/GPU times go down below 2% (or less), as long as you don't update anything faster than 0.5Hz (or so).
But that's neither finished yet nor pushed here.

Besides, I'm also looking into python-skia for a canvas implementation but then will do a "feature freeze",
since it then probably covers all of my current use cases and I'm not "addicted" to GUI-programming.
Altogether, I think DearPyGui and this here are very different in terms of Layouting, Event Processing
(I mean threading, asynio etc.) and of course the provided/created API in Python. This is also why I said,
that redesigning DearPyGui is not doable (for me) in time (if even possible).
If you like some/any of the ideas here, feel free to copy or merge them into DearPyGui.

**Comment by 0lru** [comment]
@DataExplorerUser: Maybe two more serious differences are now.. it's "supporting" asyncio and lazy drawing.
This together with threading took a bit longer to implement .. if you don't modify the UI, CPU/GPU usage now goes down < %1

**Comment by hoffstadt** [comment]
FYI, we did finally add the option for:

> Needed some way to "throttle down" the GPU-fps if no user input is given (for reducing thermal heat :-D on a pc that runs 24/7)

**Comment by 0lru** [comment]
Hm. Meanwhile, I've added some python-skia:
https://github.com/0lru/p3ui/blob/main/python/canvas/main.py.
https://raw.githubusercontent.com/0lru/p3ui/main/doc/canvas.gif

Still, I would still wish for something like a stable and complete azul.
UI-development is...

**Comment by 0lru** [comment]
@hoffstadt Out of interest: Did you ever try out subinterperters? I think your implementation needs to hold the gil "always", right?

**Comment by hoffstadt** [comment]
I did not. They still seemed "experimental". Have you yet? 

We only acquire the GIL when a callback needs to be ran or we need to use the python c api (which we try to minimize).

**Comment by 0lru** [comment]
No. I was asking because of the lambda expressions that you can use for the tick labels as an example. Another use case would be, that you render custom widgets in Python to some texture (with Skia, as an example) in the GUI thread (depending on the current sizing and coloring)... In consequence, for doing such kinds of things, you'd have to use another scripting language (Lua.. JavaScript...) or multiprocessing. Again, It'd become more and more a browser-like thing .. *g*.

**Comment by 0lru** [comment]
Finally, regardless of the api/layouting, I want it to look more like that:
![](https://raw.githubusercontent.com/0lru/p3ui/main/doc/scr6.png)

**Comment by hoffstadt** [comment]
I see. That sounds good and I imagine our similarities will continue to diverge in the future. We plan on moving more towards games, 3D, real time tooling etc. and focusing less on just UI only applications. We prefer to work more in these areas anyway. Our time is now 50% on direct UI work and 50% on a Vulkan renderer. We imagine more will shift towards the renderer as time goes on. We figured DPG will never be able to truly compete with full UI libraries like PyQt, wxWidgets, etc. for large UI applications so it's pointless to try. And even if it could, it wouldn't be any fun for us. 

There are now 5 or so python UI libraries made with imgui and that number will continue to grow as more Python/C/C++ programmers come across imgui armed with pybind and the imgui examples on setting up basic graphics pipelines to get imgui on the screen. So we'd like to focus more on what we enjoy and what isn't as saturated in the python ecosystem... real time graphics.

**Comment by 0lru** [comment]
To be honest. I think ImPlot is the project that should get more attention. What I want to have is a "nicely shaded" asyncio, python-rust-c++-ui (via binding code generation) with good plotting libraries that I can reuse in other projects.  ImGui may act still as a composition layer (see [here](https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome/)), but I'm not sure if I keep it at all, provided that I will continue to invest time here. Concerning subinterpreters: I read that: https://lukasz.langa.pl/5d044f91-49c1-4170-aed1-62b6763e6ad0/ and think your threading-pattern (extra thread for notifications besides the render-thread for avoiding the Gil ) is a very suitable, nice solution. I won't do any 3D (besides css-like rotations.. maybe). More focussing on technical applications still (ImPlot, Matplotlib...).
